### ISSUE TITLE
getIndex is not working  correctly

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebAppsLabs#101]
I have been working on this issue for a bit now but have not been able to make any progress on determining where it is breaking. My best guess is that either `self` is not being set/called properly or that something involving `arg` is mesed up. I have determined that the appropriate return in `makeFunctionFromArg` is selected, but that is about it. If @skiadas could provide some insight into this problem it would be very helpful.

**Comment by skiadas** [comment]
@TrikkStar take a closer look at `self.length` and what it actually equals and how you use it in the for loop in getIndex.
