### ISSUE TITLE
Implement regular expressions for get, has, and filter

### ISSUE THREAD

**Issue by ShelbyRB** [TrikkStar/WebAppsLabs#103]
Okay, so this is the last part that we still need to make for implementation before we turn our focus back to testing.  Regular expressions (regex) can be stored as a variable and are applied to task.title and can be matched to a string.  So, give a regular expression and a string (i.e. task.title), we apply a match method to tell us if the regex matches the string or not.  It's in the class notes on regular expressions towards the end.  You don't need to do anything fancy.  Just test it on each task's title.

**Comment by TrikkStar** [comment]
Closed due to redundant issue. This was already opened in #102 Please reference all future problems with it there.
