### ISSUE TITLE
Problem implimenting itterator

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebAppsLabs#132]
While attempting to impliment implimenting iterator I keep having errors originating in iterator.js, will be asking @skiadas if he know what is the root of the problem.

**Comment by skiadas** [comment]
Did you fix the end of the iterator.js file to say �module.exports� instead of �module.export�?

Haris Skiadas
Hanover College

**Comment by TrikkStar** [comment]
I'm now having an issue where my next() function loops somehow untill it crashes the program.

**Comment by skiadas** [comment]
Hm well first of all the function you have as "next" atm doesn't seem to return any values.

Also your function "next" doesn't need to call hasNext, it can immediately return the next element. It is the responsibility of the user of the iterator to make sure that they only call "next" after a successful "hasNext".

**Comment by TrikkStar** [comment]
But when I have it return the next value like so, it still has the same problem.

**Comment by skiadas** [comment]
Are you sure hasNext uses isLast properly?

**Comment by TrikkStar** [comment]
No. I will have to look at isLast.
