### ISSUE TITLE
About iterate and reverseIterate from

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebAppsLabs#133]
@skiadas I havent gotten to reverseItterate yet but I'm completely stuck on what to do. I'm not sure if I'm just using the methods wrong or what.

**Comment by skiadas** [comment]
Hm well you can either create a "reverseIterator" so to speak, or just manually navigate the list, but it is a double-linked circular list, so you probably for the most part just need to replace `next` with `prev` I would think.

**Comment by TrikkStar** [comment]
That makes sense, though I see I wasn't quite clear in where I was getting stuck. In my itterateFrom() method I'm trying to use the fromArray() method given to us in iterator.js, but am getting back an iterator object with whose next and hasNext values arre just functions. I'm not sure how exactly I am useing the method wrong but can only assume that I am.

**Comment by skiadas** [comment]
Hm, yeah I don�t see why you would need to use fromArray. Why don�t you do something very similar to what you did for your �iterator� method? It should be the same, other than what the starting point is. In fact, you can probably call �iterateFrom� to implement your �iterator� method.

I suppose the suggestion in the description of �iterator� misled you into thinking you have to use it for �iterateFrom� and the one after. You shouldn�t try to do that.

Haris Skiadas
Hanover College

**Comment by ShelbyRB** [comment]
Alright, I did the iterateFrom function for reverseIterateFrom, but changed all instances of "next" or "hasNext" to "previous" and "hasPrev" respectively.  I also set up the testing to be similar to the iterateFrom test (but with item order and values reversed, of course).  I'm gonna mocha it and see what happens.

**Comment by ShelbyRB** [comment]
Whoops!  Correction to that!  I was using the code for iterator() as the template for reverseIterateFrom, not iterateFrom!  My bad! :(  I'm gonna get right on that.  Also, the test code for everything except iterateFrom and reverseIterateFrom seems to be working (I mean, technically the computer says iterateFrom works too, but I only just put in the expect tests).  Sorry to be so misleading.  Also, Noah, why are you turning everything into an array?  I mean, arrays are nice, especially for testing the code cause they have set positionality and values in a set order, but it seems a bit superfluous for the actual code.

**Comment by TrikkStar** [comment]
I'm using the toArray iterator method because it is the most effective way to test to see if our list iterator methods are working as intended. Because putting the iterator into an array is the best way to look at the entire iterator at once.

**Comment by TrikkStar** [comment]
I also just realised that by not sending our iterator to an array that was where our problem was ccomming from. We weren't asking for the aproprite data to test.
