### ISSUE TITLE
is toArray working correctly?

### ISSUE THREAD

**Issue by ShelbyRB** [TrikkStar/WebAppsLabs#134]
Um...not to be a pain, but I just looked over the README file and it says the array made by toArray should contain the VALUES, not the items themselves.  The items are nodes, in a sense.  They can't just be moved around willy-nilly, which is why we make functions to insert and remove them instead of assuming they can do it themselves.  So, if we're not putting items into the array and only looking at the values, then we need to modify the tests and the code.  Again, maybe I'm mistaken.  If I'm wrong, please let me know ASAP.  Otherwise we need to fix this.

**Comment by TrikkStar** [comment]
Have you looked at the actual output of the function? If you had you would know that it is indeed only adding the values to the array.

**Comment by TrikkStar** [comment]
I double checked and it is indeed working as it is supposed to be.
