### ISSUE TITLE
fix clone in task.js

### ISSUE THREAD

**Issue by ShelbyRB** [TrikkStar/WebAppsLabs#59]
clone.tags is not working because we cannot assign to the read-only tag property.  We/I need to work around that.

**Comment by ShelbyRB** [comment]
fixed hasTag

**Comment by ShelbyRB** [comment]
Tags cannot be copied, only read.  Need to make a for or forEach loop that creates a new tag to match the old one.  In other words, an iterator/copier function.

**Comment by TrikkStar** [comment]
Was this issue actually fixed? I don't see any change related to the stated conclusion in the commit that closed the issue.

**Comment by ShelbyRB** [comment]
Turns out the ForEach loop was superfluous.  I just had to fix one line in the end.  I'm sorry I forgot to mention that.  Also, part of the reason it was failing was because of a mistake in the test code that I wrote, so that was my bad.  Anyway, it should work now.
