### ISSUE TITLE
Figure out how to handle multiple argument types in functions.

### ISSUE THREAD

**Issue by ShelbyRB** [TrikkStar/WebAppsLabs#70]
Okay.  The goal is to create a function called makePredicateFromArg that takes the kind of argument that get or has or lots of other collection functions expect and returns a function that serves the same purpose.  In makePredicateFromArg, you look at the first item, determine its type, then create and return the appropriate function.  The question we have to deal with is how to return a function that will work and where, exactly, to place the function itself.

**Comment by TrikkStar** [comment]
reference https://github.com/skiadas/WebAppsLabs/issues/7
