### ISSUE TITLE
TaskCollection.new() returns a task object instead of a collection object

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebAppsLabs#74]
Luke and Flyn were having the same problem but I don't believe they were able to fix it. @skiadas do you have any idea what might be causing this?

**Comment by skiadas** [comment]
@TrikkStar @ShelbyRB @FlynnHorrell @LukeLentz

Oh boy looks like a major typo on my part. Let me know if the following fixes it and if it does I'll email everyone:

The last line of collections.js currently says: `module.exports = Task;` It should say `module.exports = TaskCollection;`.

**Comment by TrikkStar** [comment]
That fixed it. Thank you very much
